
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 01 18:19:23 CET 2020
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 26;
  public static final int PARGAUCHE = 16;
  public static final int CSTENTIERE = 27;
  public static final int OPOU = 19;
  public static final int PLUS = 8;
  public static final int LIRE = 13;
  public static final int ECRIRE = 6;
  public static final int NON = 22;
  public static final int MOINS = 9;
  public static final int POINTVIRGULE = 5;
  public static final int BOOLEAN = 25;
  public static final int EGALE = 7;
  public static final int ENTIER = 12;
  public static final int EOF = 0;
  public static final int MULT = 10;
  public static final int OPERATION = 24;
  public static final int DIV = 11;
  public static final int PARDROITE = 17;
  public static final int PGQ = 20;
  public static final int AFFECTATION = 23;
  public static final int OPET = 18;
  public static final int error = 1;
  public static final int PPQ = 21;
  public static final int OPERNEGALE = 15;
  public static final int DEBUT = 3;
  public static final int OPEREGALE = 14;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

